name: cardiac_petct
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  device_preview: ^1.1.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Regular.ttf
