name: cardiac_petct
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  device_preview: ^1.1.0
  percent_indicator: ^4.2.3
  email_validator: ^2.1.17
  flutter_modular: ^5.0.0
  flutter_bloc: ^8.1.2
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  firebase_auth: ^4.4.0
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  flutter_svg: ^2.0.5
  carousel_slider: ^4.2.1
  mask_text_input_formatter: ^2.4.0
  localization: ^2.1.0
  flutter_localization: ^0.1.10
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/features/auth/i18n/
    - lib/features/auth/submodules/login/i18n/
    - lib/features/auth/submodules/registration/i18n/
    - lib/features/auth/submodules/email_verify/i18n/
    - lib/features/auth/domain/erros/i18n/
    - lib/features/anamnesis/presentation/i18n/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
