// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu5qPycRv8-tCaWFS0AfSoZw4WObKDBvc',
    appId: '1:647760557991:android:1f64679e17d4686d7ba882',
    messagingSenderId: '647760557991',
    projectId: 'petct-1c51a',
    databaseURL: 'https://petct-1c51a.firebaseio.com',
    storageBucket: 'petct-1c51a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRKULJ24SLAwbZThcPN_J8p1OelbEr-o',
    appId: '1:647760557991:ios:0ef2bd5fa2af253f7ba882',
    messagingSenderId: '647760557991',
    projectId: 'petct-1c51a',
    databaseURL: 'https://petct-1c51a.firebaseio.com',
    storageBucket: 'petct-1c51a.appspot.com',
    androidClientId: '647760557991-t1i5m5ppasousto3t9bph7js8prmuatm.apps.googleusercontent.com',
    iosClientId: '647760557991-8moa5leaolrep29prv7tu9b23g1k3ed9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardiacPetct',
  );
}
